// Autogenerated using npm run gen App
/*
* Copy to other files
* import App from './App';
* <App/>
*/
import styled from 'styled-components';
// import { Link, Switch, Route } from 'react-router-dom';

function App(){
  return (
    <Main>
      <AlbumBody />
    </Main>
  );
}

export default App;

const Main = styled.div`
background-color: black;
font-family: sans-serif;
padding-top: 50px;
color: white;
`;
